import type { GameConfig } from '../types/defs';

/**
 * A tiny, hand-balanced config used by engine and feature tests.
 *
 * Engine behaviour is tested against this rather than the shipping balance data
 * so that retuning the real game can never turn a determinism regression into a
 * green test run (or vice versa).
 *
 * Shape: g1 produces 1 gold/s and costs 10 gold at growth 2; g2 produces
 * 10 gold/s. `meta` is the persistent prestige currency, awarded as
 * `sqrt(runGold / 1000)`.
 */
export const TEST_CONFIG: GameConfig = {
  resources: [
    {
      id: 'gold',
      name: 'Gold',
      shortName: 'G',
      description: 'Test currency.',
      icon: 'G',
      startingAmount: '0',
      persistent: false,
      unlockedAtStart: true,
      unlock: null,
    },
    {
      id: 'meta',
      name: 'Meta',
      shortName: 'M',
      description: 'Test prestige currency.',
      icon: 'M',
      startingAmount: '0',
      persistent: true,
      unlockedAtStart: false,
      unlock: { kind: 'prestigeCountAtLeast', count: 1 },
    },
  ],
  generators: [
    {
      id: 'g1',
      name: 'Generator One',
      description: 'Tier 1.',
      tier: 1,
      produces: 'gold',
      baseRate: '1',
      cost: { kind: 'exponential', resource: 'gold', base: '10', growth: '2' },
      unlock: null,
      unlockedAtStart: true,
    },
    {
      id: 'g2',
      name: 'Generator Two',
      description: 'Tier 2.',
      tier: 2,
      produces: 'gold',
      baseRate: '10',
      cost: { kind: 'exponential', resource: 'gold', base: '1000', growth: '2' },
      unlock: { kind: 'runResourceAtLeast', resource: 'gold', amount: '100' },
      unlockedAtStart: false,
    },
  ],
  upgrades: [
    {
      id: 'boost',
      name: 'Boost',
      description: 'Doubles everything per level.',
      category: 'production',
      cost: { kind: 'exponential', resource: 'gold', base: '100', growth: '10' },
      maxLevel: 5,
      effects: [{ kind: 'globalProductionMultiplier', factor: '2' }],
      unlock: null,
      requires: [],
      persistent: false,
    },
    {
      id: 'autoG1',
      name: 'Auto One',
      description: 'Automates g1.',
      category: 'automation',
      cost: { kind: 'exponential', resource: 'gold', base: '50', growth: '1' },
      maxLevel: 1,
      effects: [{ kind: 'unlockAutomation', generator: 'g1' }],
      unlock: null,
      requires: [],
      persistent: false,
    },
    {
      id: 'metaBoost',
      name: 'Meta Boost',
      description: 'Persistent global multiplier.',
      category: 'prestige',
      cost: { kind: 'exponential', resource: 'meta', base: '1', growth: '2' },
      maxLevel: 10,
      effects: [{ kind: 'globalProductionMultiplier', factor: '3' }],
      unlock: { kind: 'prestigeCountAtLeast', count: 1 },
      requires: [],
      persistent: true,
    },
    {
      id: 'lockedUpgrade',
      name: 'Locked',
      description: 'Requires boost level 2.',
      category: 'production',
      cost: { kind: 'exponential', resource: 'gold', base: '10', growth: '1' },
      maxLevel: 1,
      effects: [{ kind: 'globalCostMultiplier', factor: '0.5' }],
      unlock: { kind: 'upgradeLevelAtLeast', upgrade: 'boost', level: 2 },
      requires: ['boost'],
      persistent: false,
    },
  ],
  story: [
    {
      id: 'intro',
      chapter: 1,
      title: 'Intro',
      speaker: null,
      body: 'It begins.',
      trigger: { kind: 'always' },
      repeatAfterPrestige: false,
      choices: [
        {
          id: 'takeGold',
          text: 'Take the gold.',
          flavour: null,
          requires: null,
          effects: [
            { kind: 'grantResource', resource: 'gold', amount: '100' },
            { kind: 'setStoryFlag', flag: 'greedy', value: true },
          ],
          nextNode: null,
        },
        {
          id: 'takePower',
          text: 'Take the power.',
          flavour: null,
          requires: null,
          effects: [{ kind: 'globalProductionMultiplier', factor: '2' }],
          nextNode: 'branch',
        },
      ],
    },
    {
      id: 'branch',
      chapter: 1,
      title: 'Branch',
      speaker: null,
      body: 'A consequence.',
      trigger: null,
      repeatAfterPrestige: false,
      choices: [],
    },
    {
      id: 'milestone',
      chapter: 1,
      title: 'Milestone',
      speaker: null,
      body: 'Five hundred.',
      trigger: { kind: 'lifetimeResourceAtLeast', resource: 'gold', amount: '500' },
      repeatAfterPrestige: false,
      choices: [],
    },
    {
      id: 'everyRun',
      chapter: 2,
      title: 'Every Run',
      speaker: null,
      body: 'Again.',
      trigger: { kind: 'generatorCountAtLeast', generator: 'g1', count: '3' },
      repeatAfterPrestige: true,
      choices: [],
    },
  ],
  prestige: {
    currency: 'meta',
    sourceResource: 'gold',
    requirement: '1000',
    divisor: '1000',
    exponent: 0.5,
    gainMultiplier: '1',
    shardBonus: '0',
    shardBonusExponent: 1,
  },
  offline: {
    minElapsedMs: 1_000,
    maxElapsedMs: 3_600_000,
    efficiency: 0.5,
    stepMs: 1_000,
    maxSteps: 1_000,
    automationEnabled: true,
  },
  time: {
    tickIntervalMs: 100,
    maxTickMs: 5_000,
    maxBackwardDriftMs: 5_000,
    maxForwardDriftMs: 30_000,
  },
  formatting: {
    notation: 'standard',
    plainBelow: '1e6',
    decimalPlaces: 2,
    smallDecimalPlaces: 2,
    suffixSeparator: ' ',
    groupSeparator: ',',
  },
  bulkBuy: { options: [1, 10, 100, -1], maxOption: -1, defaultOption: 1 },
  persistence: { storageKey: 'emberfall.test.save', saveIntervalMs: 10_000 },
};

export const TEST_EPOCH = 1_700_000_000_000;
